### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by gogasebi** [stytchauth/stytch-ios#226]
Hi,
I saw that Stytch is not reporting the privacy manifest. Is this something you are working on?
Will it be released soon?

**Comment by jhaven-stytch** [comment]
Hi @gogasebi,

This isn't something we were aware of, so thanks for bringing it to our attention. I've gone ahead and filed a ticket for us to generate one for the next release.

**Comment by gogasebi** [comment]
Thank you!

**Comment by nidal-stytch** [comment]
@gogasebi we have added a privacy manifest in this PR https://github.com/stytchauth/stytch-ios/pull/247.
