### ISSUE TITLE
Stitch can't compile on latest Xcodes

### ISSUE THREAD

**Issue by kylebrowning** [stytchauth/stytch-ios#278]
More information here, but simply, just need to update PhoneNumberKit

https://github.com/marmelroy/PhoneNumberKit/releases/tag/3.8.0

**Comment by jhaven-stytch** [comment]
Thanks for reporting this. I believe we previously had an issue with 3.7.0, let me see if that's still the case, and if not, we'll get the version bumped!

**Comment by jhaven-stytch** [comment]
Ok, version 0.41.0 should be good to go. Thanks again for reporting this!

**Comment by kylebrowning** [comment]
No problem. Next time can you include my commit so I get credit? On Aug 14, 2024, at 11:44 AM, Jordan Haven ***@***.***> wrote:﻿
Ok, version 0.41.0 should be good to go. Thanks again for reporting this!
